== Components Object

Holds a set of reusable objects for different aspects of the OAS. All objects defined within the components object will have no effect on the API unless they are explicitly referenced from properties outside the components object.


.Fix Fields
[cols="1,1,1,3", options="header"]
|===
|Field Name
|Type
|Required
|Description

|schemas
|Map[string, Schema Object | Reference Object]
|N
|An object to hold reusable Schema Objects.

|responses
|Map[string, Response Object | Reference Object]
|N
|An object to hold reusable Response Objects.

|parameters
|Map[string, Parameter Object | Reference Object]
|N
|An object to hold reusable Parameter Objects.

|examples
|Map[string, Example Object | Reference Object]
|N
|An object to hold reusable Example Objects.

|requestBodies
|Map[string, Request Body Object | Reference Object]
|N
|An object to hold reusable Request Body Objects.

|headers
|Map[string, Header Object | Reference Object]
|N
|An object to hold reusable Header Objects.

|securitySchemes
|Map[string, Security Scheme Object | Reference Object]
|N
|An object to hold reusable Security Scheme Objects.

|links
|Map[string, Link Object | Reference Object]
|N
|An object to hold reusable Link Objects.

|callbacks
|Map[string, Callback Object | Reference Object]
|N
|An object to hold reusable Callback Objects.

|===

[NOTE]
所有的field name必须匹配表达式## ``^[a-zA-Z0-9\.\-_]+$##``

.Field Name Examples:
====
User
User_1
User_Name
user-name
my.org.User
====

.Components Object Example
====
[src,json]
----
"components": {
  "schemas": {
    "GeneralError": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Category": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "Tag": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    }
  },
  "parameters": {
    "skipParam": {
      "name": "skip",
      "in": "query",
      "description": "number of items to skip",
      "required": true,
      "schema": {
        "type": "integer",
        "format": "int32"
      }
    },
    "limitParam": {
      "name": "limit",
      "in": "query",
      "description": "max records to return",
      "required": true,
      "schema" : {
        "type": "integer",
        "format": "int32"
      }
    }
  },
  "responses": {
    "NotFound": {
      "description": "Entity not found."
    },
    "IllegalInput": {
      "description": "Illegal input for operation."
    },
    "GeneralError": {
      "description": "General Error",
      "content": {
        "application/json": {
          "schema": {
            "$ref": "#/components/schemas/GeneralError"
          }
        }
      }
    }
  },
  "securitySchemes": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "header"
    },
    "petstore_auth": {
      "type": "oauth2",
      "flows": {
        "implicit": {
          "authorizationUrl": "http://example.org/api/oauth/dialog",
          "scopes": {
            "write:pets": "modify pets in your account",
            "read:pets": "read your pets"
          }
        }
      }
    }
  }
}
----

[src, yml]
----
components:
  schemas:
    GeneralError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Tag:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  parameters:
    skipParam:
      name: skip
      in: query
      description: number of items to skip
      required: true
      schema:
        type: integer
        format: int32
    limitParam:
      name: limit
      in: query
      description: max records to return
      required: true
      schema:
        type: integer
        format: int32
  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
    petstore_auth:
      type: oauth2
      flows: 
        implicit:
          authorizationUrl: http://example.org/api/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
----
====