= 艾宾浩斯遗忘曲线
:page-title: "艾宾浩斯遗忘曲线"
:page-layout: post
:page-permalink: ebbinghaus.html
:page-date:   2020-06-26 00:08:20 +0800
:page-categories: miscellaneous


遗忘曲线由德国心理学家艾宾浩斯(H.Ebbinghaus)研究发现，描述了人类大脑对新事物遗忘的规律。人体大脑对新事物遗忘的循序渐进的直观描述，人们可以从遗忘曲线中掌握遗忘规律并加以利用，从而提升自我记忆能力。该曲线对人类记忆认知研究产生了重大影响。

== 一般规律

德国心理学家艾宾浩斯(H.Ebbinghaus）研究发现，遗忘在学习之后立即开始，而且遗忘的进程并不是均匀的。最初遗忘速度很快，以后逐渐缓慢。他认为"保持和遗忘是时间的函数"，他用无意义音节（由若干音节字母组成、能够读出、但无内容意义即不是词的音节）作记忆材料，用节省法计算保持和遗忘的数量。 并根据他的实验结果绘成描述遗忘进程的曲线，即著名的艾宾浩斯记忆遗忘曲线。

.记忆间隔表
[cols="1,2", options="header"]
|===
|时间间隔	
|记忆量

|刚记完
|100%

|20分钟后
|58.2%

|1小时后
|44.2%

|8~9小时后
|35.8%

|1天后
|33.7%

|2天后
|27.8%

|6天后
|25.4%
|===

== 曲线

根据我们所知道的，记忆的保持在时间上是不同的，有短时的记忆和长时的记忆两种。

输入的信息在经过人的注意过程的学习后，便成为了人的短时的记忆，但是如果不经过及时的复习，这些记住过的东西就会遗忘，而经过了及时的复习，这些短时的记忆就会成为了人的一种长时的记忆，从而在大脑中保存着很长的时间。他得出一些关于记忆的结论。他选用了一些根本没有意义的音节（由两个辅音夹着一个元音构成的无意义的三字母单兀，例如CEG，DAX。

image::https://bkimg.cdn.bcebos.com/pic/242dd42a2834349bfaa40070c9ea15ce37d3bea1?x-bce-process=image/watermark,g_7,image_d2F0ZXIvYmFpa2U4MA==,xp_5,yp_5[遗忘曲线]

他经过对自己的测试，得到了一些数据。

然后，艾宾浩斯又根据了这些点描绘出了一条曲线，这就是非常有名的揭示遗忘规律的曲线：艾宾浩斯遗忘曲线，图中竖轴表示记忆程度（用来表示机械记忆的保持程度），横轴表示时间（天数），曲线表示机械学习实验的结果。

这条曲线告诉人们在学习中的遗忘是有规律的，遗忘的进程不是均衡的，不是固定的一天丢掉几个，转天又丢几个的，而是在记忆的最初阶段遗忘的速度很快，后来就逐渐减慢了，到了相当长的时候后，几乎就不再遗忘了，这就是遗忘的发展规律，即"先快后慢"的原则。观察这条遗忘曲线，你会发现，学得的知识在一天后，如不抓紧复习，就只剩下原来的25%。随着时间的推移，遗忘的速度减慢，遗忘的数量也就减少。有人做过一个实验，两组学生学习一段课文，甲组在学习后不久进行一次复习，乙组不予复习，一天后甲组保持98%，乙组保持56%；一周后甲组保持83%，乙组保持33%。乙组的遗忘平均值比甲组高。


== 艾宾浩斯

保持和遗忘是一对冤家对头。你对以前学过的知识能够回忆起来，就是保持住了，如果回忆不起来或回忆错了，就是遗忘。

德国心理学家艾宾浩斯（Hermann Ebbinghaus）对遗忘现象做了系统的研究，他用无意义的音节作为记忆的材料，把实验数据绘制成一条曲线，称为艾宾浩斯遗忘曲线。

image::https://bkimg.cdn.bcebos.com/pic/b3fb43166d224f4a1a68b9ee09f790529922d15e?x-bce-process=image/watermark,g_7,image_d2F0ZXIvYmFpa2U4MA==,xp_5,yp_5[艾宾浩斯遗忘曲线]

这条曲线一般称为艾宾浩斯遗忘曲线，也称艾宾浩斯保持曲线，它的纵坐标代表保持量。曲线表明了遗忘发展的一条规律：遗忘进程是不均衡的，在识记的最初遗忘很快，以后逐渐缓慢，到了相当的时间，几乎就不再遗忘了，也就是遗忘的发展是“先快后慢”。

遗忘的进程不仅受时间因素的制约，也受其他因素的制约。学生最先遗忘的是没有重要意义的、不感兴趣、不需要的材料。不熟悉的比熟悉的遗忘的要早。

== 应用

[listing]
--
1． 第一个记忆周期：5分钟
2． 第二个记忆周期：30分钟
3． 第三个记忆周期：12小时
4． 第四个记忆周期：1天
5． 第五个记忆周期：2天
6． 第六个记忆周期：4天
7． 第七个记忆周期：7天
8． 第八个记忆周期：15天
--